config/routes.rb
Railscast::Application.routes.draw do
  resources :search_suggestions

  root :to => 'episodes#index'

  resources :plans
  resources :feedbacks
  resources :logins
  resources :subscriptions
  resources :comments
  resources :categories
  resources :episodes

  resources :users
  get "paypal/checkout", to: 'subscriptions#paypal_checkout'
  
  get  "login"    => "logins#new",     :as => "login"
  post "login"    => "logins#create",  :as => "login"

  match 'about', to: "about#index"
  match 'auth/:provider/callback',to: "logins#new"
  match '/auth/failure', to: "logins#failure"
  match 'logout', to: "logins#destroy"
  get "like/index"
  get "stars/rate"

end

app/models/login.rb
class Login < ActiveRecord::Base
  attr_accessible :email, :provider, :uid, :user_id
  belongs_to :user

  def self.find_from_hash(hash, user = nil)
  	find_by_provider_and_uid(hash[:provider], hash[:uid])
  end

  def self.find_or_create_from_hash(hash, user = nil)
  	rec = find_or_initialize_by_provider_and_uid(hash[:provider], hash[:uid].to_s)
  	rec.email = hash[:info]['email']
  	rec.save unless rec.persisted?
  	rec
  end

  def associate_user(user_id)
  	update_attributes({:user_id => user_id})
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_filter :check_session

  def new 
    render 'new' and return unless auth_hash
    omniauth =auth_hash
    session[:fb_token] = omniauth['credentials']['token'] if omniauth['provider'] == 'facebook'
    record = Login.find_or_create_from_hash(auth_hash)
    if record.user_id
      session[:user_id] = record.user_id
      if current_user.role_name == "user"
        redirect_to "/episodes"
      else
        redirect_to users_url
      end
    else
      session[:auth_id] = record.id
      session[:provider] = auth_hash[:provider]
      @user = User.new(:email => record.email)

      flash.now[:error] = "Your account is not linked with facebook"
      render "new"
    end
  end

  def create
    @user = User.authenticate(params[:email], params[:password])

    unless @user
      flash.now[:alert] = "invalid email or password"
      render 'new'
    else
      session[:user_id] = @user.id
      if session[:auth_id]
        rec = Login.find(session[:auth_id])
        rec.associate_user(@user.id)
        flash[:notice] = "your account is successfully linked with fb"
        session[:auth_id] = nil
        session[:provider] = nil
      end
      if @user.role_name == "user"
        redirect_to "/episodes"
      else
        redirect_to "/users"
      end
    end
  end

  def destroy
    session[:user_id] = nil
    session[:fb_token]= nil
    redirect_to "/episodes", :notice => "you are successfully logged out"
  end      

  def auth_hash
    request.env['omniauth.auth']
  end

  def failure
    flash.now.alert "unable to connect!!!"
    render "new"
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <tr>
    <th>Email</th>
    <th>User</th>
    <th>Uid</th>
    <th>Provider</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logins.each do |login| %>
  <tr>
    <td><%= login.email %></td>
    <td><%= login.user_id %></td>
    <td><%= login.uid %></td>
    <td><%= login.provider %></td>
    <td><%= link_to 'Show', login %></td>
    <td><%= link_to 'Edit', edit_login_path(login) %></td>
    <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<div class="login_container">
  <%= form_tag login_path, { :id => "session_form" } do %>
    <div class='title'>Sign in</div>
      
    <div class='content'>
      <div class="formRow">
        <div class="input-prepend">
          <span class="add-on" title='Email'>@</span>
          <%= text_field_tag :email, params[:email],
              {:maxlength => 100, :placeholder=> 'Your email', :autocomplete => 'off'} %>
        </div>
      </div>

      <div class="formRow">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-lock"  title='Password'></i></span>
          <%= password_field_tag :password, nil, {:maxlength => 50, :placeholder => 'Password', :autocomplete => 'off'} %>
        </div>
      </div>
    </div>

    <div class="signin-bar clearfix">
      <% if flash[:alert] == 'You are Blocked!.Email sent to your email Address' %>
      <button class="btn btn-inverse " type="submit" disabled="disabled">Sign In</button>
      <% else %>
      <button class="btn btn-inverse " id="login_btn" type="submit">Sign In</button>
      <% end %>
      <span class='pull-right'><%= link_to 'Reset My Password' %></span>
    </div>
  <% end %>
</div>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @login.email %>
</p>

<p>
  <b>User:</b>
  <%= @login.user_id %>
</p>

<p>
  <b>Uid:</b>
  <%= @login.uid %>
</p>

<p>
  <b>Provider:</b>
  <%= @login.provider %>
</p>


<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>