config/routes.rb
Railscast::Application.routes.draw do
  resources :search_suggestions

  root :to => 'episodes#index'

  resources :plans
  resources :feedbacks
  resources :logins
  resources :subscriptions
  resources :comments
  resources :categories
  resources :episodes

  resources :users
  get "paypal/checkout", to: 'subscriptions#paypal_checkout'
  
  get  "login"    => "logins#new",     :as => "login"
  post "login"    => "logins#create",  :as => "login"

  match 'about', to: "about#index"
  match 'auth/:provider/callback',to: "logins#new"
  match '/auth/failure', to: "logins#failure"
  match 'logout', to: "logins#destroy"
  get "like/index"
  get "stars/rate"

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessible :category_id, :description, :note, :picture, :title, :video, :avg_rating,
                    :view_count, :episode_type

  belongs_to :category
  has_many :likes
  has_many :comments
  has_many :stars

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "120x200>" }
	has_attached_file :video

  # Paperclip Validations
  #validates_attachment :picture, :presence => true,:content_type => { :content_type => ['image/jpeg', 'image/png'] },
      #                  :size => { :less_than => 5.megabytes}

  # validates_attachment_presence :video
  # validates_attachment_content_type :video, :content_type => ['video/ogv'],:message => "Sorry, right now we only support MP4 video"


  def self.list(keyword='', category_id='', type = '')

    #cache_key = "episodes_#{keyword}_#{category_id}"
    #Rails.cache.fetch(cache_key) do
      arel = order("created_at DESC")
      arel = arel.joins(:category).where("episodes.title like ? or categories.name like ? ",
               "%#{keyword}%",  "%#{keyword}%") if keyword.present?
      arel = arel.where("category_id = #{category_id}") if category_id.present?
      arel = arel.where("episode_type = #{type}") if type.present?
      arel.all

    #end
  end

   def nested_comments
    #raise self.comments.where(:parent_id => 0).inspect
     cmts =  self.comments
     @g = []

     cmts.each do |c|

       children = Comment.where(:parent_id => c.id)
        children = children.collect{|x| x.id }
      #end
       child = Comment.where(:id => [children])
       @g <<  [c].concat(child)
       @g <<  [c].concat(call(child))
   end

     return @g.flatten.uniq(&:id)
  end

  def call(s)
    cool = []
    s.each do|c|
      cool << Comment.where(:parent_id => [c])
      @g << cool
    end
    cool.each do|d|
      call(d)
      @g << cool
    end
  end

  def get_rating
    s = []
   # Rails.cache.fetch("rating") do
      self.stars.collect{|x| s << x.rating}
      self.avg_rating = (s.sum / s.length).round if s.length >0
   # end
  end

  def update_view_count(count)
    count.view_count = 0  if count.view_count == nil
    update_attributes(:view_count => count.view_count + 1)
  end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  skip_before_filter :check_session, :only => [:index]
    #caches_action :index

  def index
   # raise current_user.inspect
    # logger.info"*******TEST************#{params[:rating]}********"
    @episodes = Episode.list(params[:q],  params[:category_id], params[:episode_type])
  end

  def show
    @episode = Episode.find(params[:id])
    @episode.update_view_count(@episode)
    @comments = @episode.comments
    @comment = Comment.new
  end

  def new
    @episode = Episode.new
  end

  def edit
    @episode = Episode.find(params[:id])
  end

  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to episodes_path, notice: 'Episode was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url }
    end
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
	def category_list
	  Category.all
	end
	
	def episodes_list(x, y)
	  Episode.where(:category_id => x ).where("id NOT IN (?)", y)
	end
	def find_category(x)
      Episode.find(x).category_id
  end
  def comment_count(x)
   # Rails.cache.fetch("no_cmts#{x}") do
  	 x.comments.count
    #end
  end
  def parent_comment(x)
  	Comment.where(:parent_id => x) 
  end
  def category_name(x)
  	 Category.find(x).name
  end
  def search_param(x = nil)
  	x!=nil ? x : "" 
  end
  def category_param(x = nil)
  	x!=nil ? x : "" 
  end
  def vote_for_like(x)
    Like.where(:episode_id => x).where(:no_of_like => 1).count
  end
  def epi_type(params)
    if params=="0"
      return "Free Episodes"
    elsif params == "1"
      return "Pro Episodes"
    elsif params == "2"
      return "Reviced Episodes"
    end
  end

  def subscribed_user(episode)

   if current_user.try(:purchased_at) != nil && current_user.try(:purchased_at) > (Time.now - 30.days)
    return true
  else 
    return false
  end
  end
end

app/views/episodes/_form.html.erb
<%= simple_form_for @episode, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :note %><br>
  Category<br>
  <%= f.select :category_id, category_list,:prompt => "Choose a Category" %>
  <%= f.input :picture %>
  <%= f.input :video %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                episodes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<%- model_class = Episode -%>
<%= render :partial => 'form' %>

app/views/episodes/index.html.erb
<%- model_class = Episode -%>
<div class = "filter " style='position:fixed;top: 155px;padding-top: 5px;' >
  <%if params[:category_id].present? || params[:q].present? || params[:episode_type] %>
    <span > <b>Applied Filters: </b>
      <% if params[:q]!= nil %>
        <span class = 'filter1'>
        <%= params[:q]%><b style = "padding-left:10px">
        <%= link_to "x" , {:controller => 'episodes',:action => 'index',:q => nil,:category_id => params[:category_id], :episode_type => params[:episode_type] } %></b>
        </span>
      <%end%>
      <% if params[:episode_type]!= nil %>
        <span class = 'filter1'>
        <%= epi_type(params[:episode_type])%><b style = "padding-left:10px">
        <%= link_to "x" , {:controller => 'episodes',:action => 'index',:episode_type => nil,:category_id => params[:category_id], :q => params[:q] } %></b>
        </span>
      <%end%>
      <%if params[:category_id].present?%>
        <span class = 'filter1'>
        <%= category_name(params[:category_id])%><b style = "padding-left:10px">
        <%= link_to "x" ,{:controller => 'episodes',:action => 'index',
          :q => params[:q],:category_id => "", :episode_type => params[:episode_type] }%></b>
        </span>
      <%end%>
    </span>
  <%end%>
  <span class='offset7' style='color:#DE9F00;font-weight:bold'><%= @episodes.count %> Episodes</span>
</div>

<div class="epi_table span9" >

  <% if @episodes.count < 1 %>
    <span class = "no_records">No episodes found.<%=link_to "See all episodes.",
    episodes_path%></span>
  <%end%>

  <% if params[:view_name] == 'grid' %>

   <% @episodes.each do |episode| %>

   <!--<%Rails.cache.fetch("link_to_episode_#{episode}") %> -->

     <span class = "span2 pull-left">
        <%= link_to (image_tag episode.picture.url(:thumb),:class => 'row-fluid grid'),
        episode_path(episode)  %>
        <%= "#{episode.id} "%><%= link_to " #{episode.title}", episode_path(episode) %>
      </span>
      <%end%>

  <% elsif params[:view_name] == 'line' %>

    <table class="table epi_line_view span9 table-bordered" >
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Comments</th>
          <th>Duration</th>
          <th>Released</th>
        </tr>
      </thead>
      <tbody>
        <% @episodes.each do |episode| %>
          <tr>
            <td><%= episode.id %></td>
            <td><%= link_to episode.title, episode_path(episode) %></td>
            <td><%= comment_count(episode)%> comments</td>
            <td><%= "7 minutes"%></td>
            <td><%= episode.created_at.strftime("%b %d %Y") %></td>
            <%if current_user.role_name=="admin"%>
              <td><%= link_to "edit", edit_episode_path(episode), :class => "btn btn-mini"%></td>
              <td><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      episode_path(episode),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %></td>
            <%end%>
          </tr>
        <% end %>
        </tbody>
    </table>

  <% else %>

    <% @episodes.each do |episode| %>

      <div class='span10 row-fluid'>
        <%= image_tag episode.picture.url(:thumb), :class => 'span3 img' %>
        <span class = "span9">
          <span class = "epi_id">Episode #<%= episode.id %> - <%= episode.created_at.strftime("%B %d %Y") %>- <%= comment_count(episode)%>Comments</span>

           <span class = "pull-right like_div"><%= button_tag "#{vote_for_like(episode)} Likes", :class => "btn-success like " %>
           <%= button_tag "#{episode.view_count} Views", :class => "btn like " %></span>
            <table class='star-rating pull-right'>
              <tr> <th>Rating</th></tr><tr><th>

              <% value = 5 - episode.get_rating.to_i %>
              <% episode.get_rating.to_i.times do |s| %>
                  <%= image_tag 'star-on.png', :class => 'rating', :id => "rate#{s}" %>
                <% end %>

                <% value.times do |s| %>
                  <%= image_tag 'star-off.png', :class => 'rating', :id => "rate#{s}" %>
                <% end %>
                  </th> </tr>
            </table>


            <br>

          <span class="epi_title"><%= link_to episode.title, episode_path(episode) %></span> <br>
          <span class='epi_note'><%= episode.description %>

            <span class = "epi_id">(<%="7 minutes"%>)</span></span><br>
            <%if  current_user.present? && (subscribed_user(episode) || episode.episode_type == 0 || current_user.purchased_at != nil) %>
            <span ><%= link_to "Watch Episode",episode.video.url, :class => 'btn epi_btn' %> </span>
            <span class ='span3'>
              <%= link_to "Read Episode",episode_path(episode), :class => 'btn epi_btn '%></span>
             </span>
          <% else %>
             <span ><%= link_to "Subscribe to Watch Episode","/subscriptions?id=#{episode.id}", :class => 'btn epi_btn btn-primary ' %>

          <% end %>
        </span>

      </div>
      <span class = "span9"> <hr></span>
    <%end%>
  <%end%>
</div>
<div class = "fix span2  pull-right ">
  <div class = "change_view span2   ">
    View
    <span class="view"><%= link_to (image_tag "normal.png"), {:controller => 'episodes',
      :action => 'index', :view_name => 'normal', :q => params[:q],
      :category_id => params[:category_id], :episode_type => params[:episode_type] } %></span>
    <span class="view"><%= link_to (image_tag "line.png"), {:controller => 'episodes',
      :action => 'index', :view_name => 'line', :q => params[:q],
      :category_id => params[:category_id], :episode_type => params[:episode_type] } %></span>
    <span class="view"><%= link_to (image_tag "grid.png"), {:controller => 'episodes',
      :action => 'index', :view_name => 'grid', :q => params[:q],
      :category_id => params[:category_id], :episode_type => params[:episode_type] } %></span>
  </div>
   <div class = "category_list span2  ">
    <h3>Types</h3>
    <ul>


    <li><%= link_to "Free Episodes", {:controller => 'episodes',:action => 'index',
      :q => params[:q], :category_id => params[:category_id],:view_name => params[:view_name],
      :episode_type => 0 }, :class => "mylink"%>  </li>
    <li><%= link_to "Pro Episodes", {:controller => 'episodes',:action => 'index',
      :q => params[:q], :category_id => params[:category_id],:view_name => params[:view_name],
      :episode_type => 1 }, :class => "mylink"%>  </li>
    <li><%= link_to "Revices Episodes", {:controller => 'episodes',:action => 'index',
      :q => params[:q], :category_id => params[:category_id],:view_name => params[:view_name],
      :episode_type => 2 }, :class => "mylink"%>  </li>
    <ul>
  </div>
  <div class = "category_list span2  ">
    <h3>Categories</h3>
    <ul>

      <% cache("all_categories_#{params[:q]}") do %>
    <% category_list.each do |e| %>

    <li><%= link_to e.name, {:controller => 'episodes',:action => 'index',
      :q => params[:q], :category_id => e,:view_name => params[:view_name],
      :episode_type => params[:episode_type] }, :id => "mylink#{e.id}", :class => "mylink"%>  </li>
    <% end %><ul>
    <%end%>
  </div>
</div>

app/views/episodes/new.html.erb
<%- model_class = Episode -%>

<%= render :partial => 'form' %>

app/views/episodes/show.html.erb
<%- model_class = Episode -%>

<!-- <span class = "span2 pull-right">
</span> -->

<table class='star-rating pull-right'>
  <% rate =  @episode.stars.where(:user_id => current_user.id).last %>
  <tr> <th> Rating</th></tr><tr><th>
  <% if rate == nil  %>
    <% (1..5).each do |s| %>
      <%= image_tag 'star-off.png', :class => 'rating', :id => "rate#{s}",
        :onmouseover =>"change_star_image(#{s}, #{@episode.id})",:value => s %>
    <% end %>
  <%else%>
    <% value = 5 - rate.rating.to_i %>
    <% rate.rating.to_i.times do |s| %>
      <%= image_tag 'star-on.png', :class => 'rating', :id => "rate#{s}" %>
    <% end %>
    <% value.times do |s| %>
      <%= image_tag 'star-off.png', :class => 'rating', :id => "rate#{s}" %>
    <% end %>
  <%end%>
  </th> </tr>
</table>

<div>
    <div class='span12 row-fluid'>
       <%= image_tag @episode.picture.url(:thumb), :class => 'span3 img' %>
      <span class = "span8">
        <span class = "epi_id">Episode #<%= @episode.id %> - <%= @episode.created_at.strftime("%B %d %Y") %>- <%= comment_count(@episode)%>Comments</span><br>
        <span class="epi_title"><%=  @episode.title %></span><br>
        <span class='epi_note'><%= @episode.description %></span><br>
        <%#raise [].inspect%>
        <%if  current_user.present? && subscribed_user(@episode) || @episode.episode_type == 0 || current_user.purchased_at != nil %>
        <span class = ' '><%=link_to "Click here to play", @episode.video.url, :class => "btn epi_btn" %></span>
        <%else%>
             <span ><%= link_to "Subscribe to Watch Episode","/subscriptions?id=#{@episode.id}", :class => 'btn epi_btn btn-primary ' %>
        <% end %>
        <span class = 'like pull-right', text = <%="#{@episode.id}"%>>Was this episode useful to you?
          <%=button_tag "Yes", :class => "btn key", :value => 1 %>
          <%=button_tag "No", :class => "btn key", :value => 0 %></span>
          <span class = 'feed pull-right'>Thanks for your feedback!</span>
      </span>
    </div>
</div><br>

<div class = "span9 tab-menu">

  <ul class="nav nav-tabs" id="myTab">
    <li ><a href="#note" data-toggle="tab">Note</a></li>
    <li class = "active"><a href="#comment" data-toggle="tab">
      <%="#{comment_count(@episode) }"%> Comments</a></li>
    <li><a href="#same" data-toggle="tab">Similar Episodes</a></li>
  </ul>

  <div class="tab-content span10">
    <div class="tab-pane span8  " id="note">
      <div id="tabs1-note", class="span8">
         <%= @episode.note %>
      </div>
    </div>

    <div class="tab-pane span8 active" id="comment">
       <% @episode.nested_comments.each do |f| %>
          <% if f.level ==0  %>
          <div id = "comment_disp", class = "main_cmt pull-right ">
            <%elsif f.level ==1 %>
            <div id = "comment_disp", class = "sub1_cmt pull-right">
            <%elsif f.level ==2 %>
             <div id = "comment_disp", class = "sub2_cmt pull-right">
            <%elsif f.level ==3 %>
             <div id = "comment_disp", class = "sub3_cmt pull-right">
              <%elsif f.level ==4 %>
             <div id = "comment_disp", class = "sub4_cmt pull-right">
              <%elsif f.level ==0 && f.parent_id == 0 %>
              <div id = "comment_disp", class = "sub3_cmt pull-right">
            <%end%>

            <div id = "comment_name">
              <div class = 'comment_border'> <b class = "comment_name"><%= f.name %> </b> on

              <%= distance_of_time_in_words(f.created_at, Time.now)%> ago</div>
            </div>
            <p style="margin:3px 0px 3px 20px">
              <%= f.description%>
            </p>
            <%= button_tag "reply" , :class => 'comment_reply'%>
          </div>
           <div class ="comt reply hi ">
            <div class = 'comment_border span6'> <b class = "comment_name"><%= current_user.name %> </b> on
               <%= f.created_at.strftime("%Y-%m-%d %H:%M:%S")%></div>

            <%= form_for (@comment) do |x|%>
                <%= x.text_area :description, :size => "60*100"%><br>
                <%= x.hidden_field :episode_id, :value => "#{@episode.id}"%>
                <%= x.hidden_field :name, :value => current_user.name%>
                <%= x.hidden_field :parent_id,  :value => f.id %>
                <%= x.hidden_field :user_id, :value => current_user.id%>
                <b > <%= x.submit "Post Comment" %></b>
            <%end%>
          </div>
        <%end%>

        <div class ="comt">
          <div class = 'comment_border span6'> <b class = "comment_name"><%= current_user.name %> </b> on
            <b class = "comment_name">
           <%= "##{@episode.id} #{@episode.title} " %></b>  <%= Time.now.strftime("%Y-%m-%d %H:%M:%S")%></div>
          <%= form_for (@comment) do |x|%>
          <%= x.text_area :description, :size => "60*100"%><br>
          <%= x.hidden_field :episode_id, :value => "#{@episode.id}"%>
          <%= x.hidden_field :name, :value => current_user.name%>
          <%= x.hidden_field :user_id, :value => current_user.id%>
          <b > <%= x.submit "Post Comment" %></b>
          <%end%>
        </div>
    </div>

    <div class="tab-pane span8 " id="same">

      <% episodes_list(find_category(params[:id]), params[:id]).each do |episode| %>
        <div class='span5 row-fluid'>
          <%= image_tag episode.picture.url(:thumb), :class => 'span3 img' %>
          <span class = "span9">
            <span class = "epi_id">Episode #<%= episode.id %> - <%= episode.created_at.strftime("%B %d %Y") %>- <%= comment_count(episode)%>Comments</span><br>
            <span class="epi_title"><%= link_to episode.title, episode_path(episode) %></span><br>
            <span class='epi_note'><%= episode.description %>  <span class = "epi_id">(<%="7 minutes"%>)</span></span><br>
            <span class = 'btn epi_btn span3'><%= link_to "Watch Episode",episode.video.url %> </span>
            <span class = 'btn  epi_btn span3'><%= link_to "Read Episode",episode_path(episode) %></span>
          </span><span class = "span12"> <hr></span>
        </div>
      <%end%>

    </div>

  </div>
</div>