config/routes.rb
Railscast::Application.routes.draw do
  resources :search_suggestions

  root :to => 'episodes#index'

  resources :plans
  resources :feedbacks
  resources :logins
  resources :subscriptions
  resources :comments
  resources :categories
  resources :episodes

  resources :users
  get "paypal/checkout", to: 'subscriptions#paypal_checkout'
  
  get  "login"    => "logins#new",     :as => "login"
  post "login"    => "logins#create",  :as => "login"

  match 'about', to: "about#index"
  match 'auth/:provider/callback',to: "logins#new"
  match '/auth/failure', to: "logins#failure"
  match 'logout', to: "logins#destroy"
  get "like/index"
  get "stars/rate"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :email, :message, :name

  validates :name,           :presence => true, :format  => { :with => /^[A-z .'-]+$/,
                             :message  => "Enter only characters",:allow_blank => true },
                             :length   => { :maximum => 15,  :message => "Enter within 5 - 15 characters ",
                             :allow_blank => true   }
	validates :email  ,        :presence => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/,:message  => "Invalid Email Format"},
                             :length   => {:maximum=>150, :allow_blank => true}  
	validates :message,        :presence => true, :length => {:maximum=>500, :allow_blank => true}  
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
 skip_before_filter :check_session
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

      if @feedback.save
        redirect_to "/episodes", notice: "Thank you for the feedback."
      else
        render "new" 
      end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<div id = "feedback", class = "span8">
  <h2 class = "bar  row-fluid"> Feeadback </h2>
  <div class = "feedback_mail span8 row-fluid">
    You can also contact <%= link_to "@railscasts", "http://facebook.com/railscasts" %> on Facebook, or send an email to <%= mail_to "feedback@railscasts.com" %>.
  </div>
    <%= simple_form_for @feedback, :html => { :class => 'form-horizontal span8' } do |f| %>
    <table class = "feedback_table span6"><tr><th>Your Name </th><td><%= f.text_field( "name") %>
      <span class= "error"> <%= @feedback.errors[:name].to_sentence %></span></td></tr>
           <tr><th>Your Email Address </th><td><%= f.email_field( "email") %>
            <span class= "error"> <%= @feedback.errors[:email].to_sentence %></span></td></tr>
           <tr><th>Message </th><td><%= f.text_area( :message ,  :size => "50x10")%>
            <span class= "error"> <%= @feedback.errors[:message].to_sentence %></span></td></tr>
           <tr><th></th><td><%= f.submit %></td></tr>
    </table>
    <%end%>
</div>
<div class = "feedback_info span3">
  <h4>Please send feedback about:</h4>

<ul><li>Problems with existing episodes</li>
<li>Ideas for future episodes</li>
<li>Anything about this site</li></ul><br>
Unfortunately I am unable to answer generic Rails questions which are not specific to RailsCasts. For this I recommend asking on one of the following forums.
<br>
<ul><li>Rails Talk Mailing List</li>
<li>Stack Overflow</li>
<li>Rails Forum</li></ul>
</div>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/new.html.erb
<%= render 'form' %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @feedback.name %>
</p>

<p>
  <b>Email:</b>
  <%= @feedback.email %>
</p>

<p>
  <b>Message:</b>
  <%= @feedback.message %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>